#!/usr/bin/env bash
# Installs and setup haproxyi.

# Update package list
sudo apt -y update

# Install HAProxy
sudo apt -y install haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 476269-web-01 100.25.156.92:80 check
   server 476269-web-02 52.87.219.72:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start

