#!/usr/bin/env bash
#Prints "Best School" 10 times, and "Hi" the 9th time.
MESSAGE="Best School"

COUNT=0
while [ $COUNT -lt 10 ]; do
   if [ $COUNT = 8 ]; then
	   echo "$MESSAGE"
	   echo "Hi"
      ((COUNT++))
   else
      echo "$MESSAGE"
      ((COUNT++))
   fi
done
